version: '3.8'

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis
      - redis-etc:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - redis-network